theme: minima
title: Victor Salvia Punsoda
author: Victor
description: Feel free to send me a message if you want to talk.
logo: ![image](/profile.jpeg)
email: [pusavi17@gmail.com]
github_username: VictorSP17
