theme: jekyll-theme-minimal
title: [Victor Salvia Punsoda]
description: [Feel free to send me a message if you want to talk.]
logo: ![image](/profile.jpeg)
description: [pusavi17@gmail.com]
description: [VictorSP17](https://github.com/VictorSP17)
