theme: minima
title: Victor Salvia Punsoda
author: Victor
description: Feel free to send me a message if you want to talk.
logo: ![image](/profile.jpeg)
email: [pusavi17@gmail.com]
github_username: VictorSP17
linkedin: https://www.linkedin.com/in/víctor-salvia-punsoda-6202b2b7 
