theme: minima
title: Victor Salvia Punsoda
author: Victor
description: Please, do not hesitate to contact me if you want to chat.
logo: ![image](/profile.jpeg)
email: [pusavi17@gmail.com]
github_username: VictorSP17
